module.exports = {
    extends: ['@commitlint/config-conventional'],
    rules: {
        'subject-case': [2, 'always', 'sentence-case'],
        'header-max-length': [1, 'always', 80],
        'scope-enum': [2, 'always', [
            'components',
            'config',
            'goals',
            'webpack',
            'eslint',
            'commitlint',
        ]],
        'type-enum': [2, 'always',
            [
                'build',
                'change',
                'chore',
                'deprecate',
                'ci',
                'docs',
                'feat',
                'fix',
                'perf',
                'refactor',
                'remove',
                'revert',
                'security',
                'style',
                'test',
            ],
        ],
    },
};
